### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by erfanimani** [quickshiftin/wfpc#5]
Hi there,

Thanks for this script - super useful.

It seems that the script doesn't follow pagination (i.e. `?p=2`). I know that it just follows the sitemap, and the sitemap doesn't contain page numbers, however since this is a cachewarmer, that could be useful too.

My suggestion is to create a flag that, which enabled, automatically tries to grab the next page by appending `?p={n+1}`, and as long as it doesn't 404, keeps incrementing `n`.

Thoughts?

**Comment by quickshiftin** [comment]
First off thanks, I'm glad you like the script!

Personally I wouldn't follow arbitrary links; if anything I would look for links on the page then follow those. That would turn this script into a full-blown spider, whereas currently it's pretty simple.
