### ISSUE TITLE
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:

### ISSUE THREAD

**Issue by psolutions-me** [quickshiftin/wfpc#7]
What is wrong there?

The website use SSL.
Need to specify in the .php file the url to sitemap?

```
root@XXX:/var/www/vhosts/domain.com/magento# php ./wfpc -k -t https://www.domain.com/sitemap.xml

PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol in /var/www/vhosts/domain.com/magento/MageCacheWarmer.php on line 180
PHP Warning:  file_get_contents(): Failed to enable crypto in /var/www/vhosts/domain.com/magento/MageCacheWarmer.php on line 180
PHP Warning:  file_get_contents(https://www.domain.com/sitemap.xml): failed to open stream: operation failed in /var/www/vhosts/domain.com/magento/MageCacheWarmer.php on line 180
Cache warmer crashed with error:
Unable to download the sitemap file at $sSitemapUrl

```

**Comment by quickshiftin** [comment]
Hmmm, what have you tried to fix it? I took a [quick look on Stackoverflow](https://github.com/quickshiftin/wfpc/issues/7) and it looks like we are setting both `verify_peer` and `verify_peer_name` when you set the `-k` option [in my project](https://github.com/quickshiftin/wfpc/blob/master/MageCacheWarmer.php#L224-L225).

You may want to try working through some of the other suggestions on that SO thread and let us know if you figure it out.

**Comment by quickshiftin** [comment]
As I have not heard back in over a year on this and have no way to reproduce, as well as support for SSL in the code, I am closing this issue.

Feel free to reopen with more detail and a reproducible example.
