### ISSUE TITLE
after crawl, site is not in varnish cache

### ISSUE THREAD

**Issue by hubertzawada** [quickshiftin/wfpc#9]
Hi!

I'm crawling my Magento 1.9 sitemap. Everything goes smoothly, at initial test I see:
Average page time is 2674.6529817581 (so many pages are not in Varnish cache)
and later, after crawl:
Finished warming your Magento site performance
Average page time (in milliseconds): 304.81739044189 (they are in Varnish for sure :))
Speedup is 88.6%

But when checking manually URLs in Chrome I see in header response Age: 0, which means that site is not in Varnish Cache. After refreshing site in Chrome, Age: >0, so the site goes to Varnish because of my visit via Chrome. It means that Varnish works, but wfpc not.

When I'm crawling again sitemap with wfpc avg resp. time is ~300 ms, so wfpc have information that sites are in Varnish, but in fact, when manually checking via Chrome they are not. Do you have any idea why?
When I'm crawling my site via SEO crawlers like Screamingfrog, they goes to Varnish with no problem.

Regards,
Hubert

**Comment by dzschille** [comment]
@hubertzawada perhaps your Varnish is configured for device detection? If yes then different user-agents use "different caches". See https://varnish-cache.org/docs/trunk/users-guide/devicedetection.html

**Comment by quickshiftin** [comment]
Hi @hubertzawada, as this is specific to your Magento cache configuration, it has nothing to do with this script. Check the advice of @hubertzawada and google around for how to troubleshoot caching of your Magento site.
